/*
	Banking using Array of Structures (Structures and Unions)
		Write a C Program to simulate Banking application that performs insertion, deletion and search on array of customer structures that includes AC No., Name, Mobile No, Address etc.
*/
#include <stdio.h>
#include <string.h>

#define ARR_SIZE	10
#define NAME_SIZE	50
#define ADD_SIZE	100
#define BASE_AC_NO	2034349800

int count = 0, last = 0;

struct customer
{
	long contact, account_num;
	char name[NAME_SIZE], address[ADD_SIZE];
};

void print_customer_data (struct customer s)
{
	printf ("\t %s holding Ac No - %li lives at %s. Contact : %li\n", s.name, s.account_num, s.address, s.contact);
}

void copy_customer_data (struct customer source, struct customer target)
{
	target.account_num = source.account_num;
	target.contact = source.contact;
	strcpy (target.name, source.name);
	strcpy (target.address, source.address);
}

void insert_customer_data (struct customer s[])
{
	if (last == ARR_SIZE)
		printf ("\t\t\t!!! Customer Records Full !!!\n");
	else
	{
		getchar ();
		printf ("\tName         : ");
		gets (s[last].name);
		s[last].account_num = BASE_AC_NO + count;
		printf ("\tAccount No.  : %li (Generated by the system)\n", s[last].account_num);
		printf ("\tAddress      : ");
		gets (s[last].address);
		printf ("\tContact      : ");
		scanf ("%li", &s[last].contact);
		while ((s[last].contact / 10000000000) || (s[last].contact / 1000000000 == 0))
		{
			printf ("\t\t\t\tRe-Enter contact correctly\n");
			printf ("\tContact      : ");
			scanf ("%li", &s[last].contact);
		}
		count++;
		last++;
	}
}

void search_customer_data_by_name (struct customer s[])
{
	char name[NAME_SIZE];
	getchar ();
	printf ("Enter the customer name : ");
	gets (name);
	for (int i = 0; i < last; ++i)
	{
		if (strcasestr (s[i].name, name))
			print_customer_data (s[i]);
	}
}

int search_customer_data_by_acno (struct customer s[], long account_num)
{
	for (int i = 0; i < last; ++i)
		if (s[i].account_num == account_num)
			return i;
	return -1;
}

void search_customer_data_by_addr (struct customer s[])
{
	char address[ADD_SIZE];
	getchar ();
	printf ("Enter the customer address : ");
	gets (address);
	for (int i = 0; i < last; ++i)
	{
		if (strcasestr (s[i].address, address))
			print_customer_data (s[i]);
	}
}

void search_customer_data_by_contact (struct customer s[])
{
	long contact;
	printf ("Enter the customer contact : ");
	scanf ("%li", &contact);
	for (int i = 0; i < last; ++i)
	{
		if (s[i].contact == contact)
			print_customer_data (s[i]);
	}
}

void search_customer_data (struct customer s[])
{
	if (last == 0)
	{
		printf ("\t\t\t!!! No Customer Data Available To Search For !!!\n");
		getchar ();
	}
	else
	{
		int param_choice;
		printf ("\nWhat do you wish to search by :\n\t1. Customer Name\n\t2. Account number\n\t3. Address\n\t4. Contact\n\t----> ");
		scanf ("%d", &param_choice);
		switch (param_choice)
		{
			case 1	: search_customer_data_by_name (s);
					break;
			case 2 	: printf ("Enter the account number : ");
					long account_num;
					scanf ("%li", &account_num);
					int i = search_customer_data_by_acno (s, account_num);
					if (i != -1)
						print_customer_data (s[i]);
					else
						printf ("\t\t\t!!! Account Number doesn't exist !!!\n");
					getchar ();
					break;
			case 3	: search_customer_data_by_addr (s);
					break;
			case 4	: search_customer_data_by_contact (s);
					getchar ();
					break;
			default	: printf ("\t\t\t!!! Invalid Choice of Parameter !!!\n");
		}
	}
}

void delete_customer_data (struct customer s[])
{
	if (last == 0)
		printf ("\t\t\t!!! No Customer Data available to delete !!!\n");
	else
	{
		long account_num;
		printf ("Enter the account number to delete : ");
		scanf ("%li", &account_num);
		int flag = search_customer_data_by_acno (s, account_num);
		if (flag != -1)
		{
			printf ("\t\tDeleting the following Record\n");
			print_customer_data (s[flag]);
			for (int i = flag + 1; i < last; ++i)
				copy_customer_data (s[i - 1], s[i]);
			last--;
		}
		else
			printf ("\t\t\t!!! Account Number doesn't exist !!!\n");
	}
}

int main ()
{
	int choice_op;
	char flag = 'y';
	struct customer ct[ARR_SIZE];

	while (flag == 'y' || flag == 'Y')
	{
		printf ("\nChoose Operation :\n\t1. Insert Customer Data\n\t2. Search Customer Data\n\t3. Delete Customer Data\n\t----> ");
		scanf ("%d", &choice_op);

		switch (choice_op)
		{
			case 1	: insert_customer_data (ct);
					getchar ();
					break;
			case 2	: search_customer_data (ct);
					break;
			case 3	: delete_customer_data (ct);
					getchar ();
					break;
			default	: printf ("\t\t\t\t!!! INVALID CHOICE !!!");
		}

		printf ("\n\t\t\tTo continue, press 'y' or 'Y' (any other character to exit) : ");
		scanf ("%c", &flag);
	}

	printf ("\t\t\tThankyou for trying this program !!!\n");

	return 0;
}
